---
- name: playbook resolution problème dns
  hosts: all
  remote_user: root
  tasks:
    - name: résolution problème dns
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver 192.168.1.1'
        line: 'nameserver 8.8.8.8'

    - name: toto et titi commande apt-get update 
      apt:
        update_cache: 'yes'
...
