---
- name: installation apache (Debian)
  apt:
    name: apache2
    state: present
  when: ansible_distribution == "Debian"

- name: installation apache (centos)
  yum:
    name: apache2
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: effacer html (CentOs)
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: mise en route du site
  copy:
    src: ./html
    dest: /var/www
...