---
- name: installation apache
  apt:
    name: apache2
    state: present

- name: effacer html
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: mise en route du site
  copy:
    src: ./html
    dest: /var/www
...