---
- name: afficher ansible distribution
  debug:
    msg: "{{ ansible_distribution }} && {{ ansible_distribution_major_version }}"

- name: import task portsentry
  import_tasks: install_portsentry_centos.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Rocky"
...
