---
- name: installation des outils sur centos
  yum:
    name:
      - nano
      - wget
      - curl
      - git
      - epel-release
      - glances
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
...