---
- name: mofification dhcp en static
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    regexp: "^BOOTPROTO="
    line: BOOTPROTO="static"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
...