---
- name: mofification dhcp en static
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    regexp: "^BOOTPROTO="
    line: BOOTPROTO="static"
    backrefs: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: parametrage des adresses ip
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    insertafter: EOF
    block: |
      IPADDR={{ network.ip }}
      NETMASK={{ network.mask }}
      GATEWAY={{ network.gateway }}
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: redemarage service réseau
  systemd:
    name: network
    state: restarted
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
...
