---
- name: mise à jour systeme debian 10
  apt:
    update_cache: 'yes'
    upgrade: 'yes'
  when: ansible_distribution == "Debian"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: mise à jour systeme centos
  yum:
    state: latest
    update_cache : 'yes'
    update_only : 'yes'
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" ansible_distribution == "Rocky"
...
