---
- name: installation fail2ban (debian)
  apt:
    state: present
    name: fail2ban
    update_cache: 'yes'
  when: ansible_distribution == "debian"

- name: installation fail2ban (centos)
  yum:
    state: present
    name: fail2ban
    update_cache: 'yes'
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Rocky"

- name: supression fichier
  file:
    path: /etc/fail2ban/jail.d/custom.conf
    state: absent

- name: creation d'un fichier sur test
  blockinfile:
    path: "/etc/fail2ban/jail.d/defaults-debian.conf"
    create: true
    block: |
      [sshd]
      enabled = true
      port = 22
      logpath = /var/log/auth.log
      maxretry = 5

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: recuperation etat jails
  shell: fail2ban-client status
...
